.\" Process this file with
.\" groff -man -Tascii skalpel-bin.1
.\"
.\"
\" ##############################################################
\" ##############################################################
\" ##
\" ## Copyright 2010 2011 John Pirie
\" ## Copyright 2010 Steven Shiells
\" ##
\" ## This file is free software: you can redistribute it and/or modify
\" ## it under the terms of the GNU General Public License as published by
\" ## the Free Software Foundation, either version 3 of the License, or
\" ## (at your option) any later version.
\" ##
\" ## This file is distributed in the hope that it will be useful,
\" ## but WITHOUT ANY WARRANTY; without even the implied warranty of
\" ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\" ## GNU General Public License for more details.
\" ##
\" ## You should have received a copy of the GNU General Public License
\" ## along with Skalpel.  If not, see <http://www.gnu.org/licenses/>.
\" ##
\" ## Authors: Steven Shiells
\" ## Date: January 2010
\" ##
\" ###############################################################
\" ###############################################################
.TH SKALPEL-BIN 1 "January 2010" Linux "User Manuals"
.SH NAME
skalpel-bin \- runs a type error slicer for SML.
.SH SYNOPSIS
skalpel-bin
.SH DESCRIPTION
Users wishing to use the skalpel-bin command should instead use the
.I skalpel
command as it allows the user to use skalpel-bin in a more user
friendly way.

.SH AUTHORS
Joe Wells  <jbw@macs.hw.ac.uk>

Vincent Rahli <rahli@macs.hw.ac.uk>

John Pirie <jp95@macs.hw.ac.uk>

Scott Fotheringham <sf47@macs.hw.ac.uk>

Mark Wyper <mw105@macs.hw.ac.uk>

Steven Shiells <ss215@macs.hw.ac.uk>

David Dunsmore <dd35@macs.hw.ac.uk>

