#!/bin/sh

###############################################################
###############################################################
##
## Copyright 2011 Heriot-Watt University
##
## This file is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This file is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Skalpel.  If not, see <http://www.gnu.org/licenses/>.
##
## Authors: John Pirie
## Date: October 2011
## Description: A pre-commit script for git to check for copyright
##              licenses (like this one)
##
################################################################
################################################################

gitConfigName=`git config user.name`

if [ "$gitConfigName" = "John Pirie" ]
then
    checkName="Heriot-Watt University"
else
    checkName=`git config user.name`
fi

grepCommand="Copyright".*"`date +%Y`[[:space:]]`echo $checkName | sed s/" "/"[[:space:]]"/g`"

for FILE in `git diff --cached --name-only`
do
    output="`cat $FILE | grep $grepCommand`"
    if [ "$output" = "" ]
    then
	echo "File \"$FILE\" does not have a copyright statement matching \"$grepCommand\""
	exit 1
    fi
done
