#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/skalpel-emacs

FLAVOR=$1
PACKAGE=skalpel-emacs

if [ ${FLAVOR} != emacs ]; then
    # if test -x /usr/sbin/install-info-altdir; then
    #     echo remove/${PACKAGE}: removing Info links for ${FLAVOR}
    #     install-info-altdir --quiet --remove --dirname=${FLAVOR} /usr/local/share/info/skalpel-emacs.info.gz
    # fi

    echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}
    rm -rf /usr/local/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
