.\" Process this file with
.\" groff -man -Tascii skalpel-emacs.1
.\"
\" ##############################################################
\" ##############################################################
\" ##
\" ## Copyright 2010, 2011 Steven Shiells
\" ## Copyright Heriot-Watt University 2011
\" ##
\" ## This file is free software: you can redistribute it and/or modify
\" ## it under the terms of the GNU General Public License as published by
\" ## the Free Software Foundation, either version 3 of the License, or
\" ## (at your option) any later version.
\" ##
\" ## skalpel-emacs is distributed in the hope that it will be useful,
\" ## but WITHOUT ANY WARRANTY; without even the implied warranty of
\" ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\" ## GNU General Public License for more details.
\" ##
\" ## You should have received a copy of the GNU General Public License
\" ## along with skalpel-emacs.  If not, see <http://www.gnu.org/licenses/>.
\" ##
\" ## Authors: Steven Shiells
\" ## Date: January 2010
\" ##
\" ###############################################################
\" ###############################################################
.TH SKALPEL-EMACS 1 "January 2010" Linux "User Manuals"
.SH NAME
skalpel-emacs \- allows the type error slicer to be run in Emacs
.SH DESCRIPTION
Allows the type error slicer to be run on SML files whilst they are
being written using the Emacs editor. The type error slicer will
highlight the pieces of source code which contribute to the error in
the actual source file itself.

For information on how to use the type error slicer in Emacs please
refer to the user guide by viewing the info file
.I Skalpel

.SH PLEASE NOTE
In order to use the type error slicer with a locally
installed version of Emacs you must load the file
.I /usr/local/share/emacs/site-lisp/skalpel-emacs/skalpel-config.el

(To save the hassle of having to do this each time you start Emacs you
may wish to load this file in your .emacs(.el) file).

.SH AUTHORS
For a list of authors, please see the user guide which is by default
installed to /usr/share/doc/skalpel/user-guide.pdf.

.SH "SEE ALSO"
skalpel(1), skalpel-bin(1), skalpel-perl-to-bash(1), skalpel-legend(1).
