#!/bin/bash


################################################################
################################################################
##
## Copyright 2010 Steven Shiells
## Copyright 2011 John Pirie
##
## This file is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This file is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with smltes.  If not, see <http://www.gnu.org/licenses/>.
##
##
## Authors: Steven Shiells, John Pirie
## Date: January 2010
## Description: This is a shell script which displays a legend
##              explaining the highlighting techniques used by
##              the type error slicer.
##
#################################################################
#################################################################

## standard
stand="\e[1;40;37m"
title="\e[4;33m"

## dark colours - normal
r="\e[1;41;37m"
p="\e[1;45;37m"
b="\e[1;44;37m"
g="\e[1;42;37m"
y="\e[1;43;37m"
o="\e[1;46;37m"

## dark colours - boxes
br="\e[4;31m"
bp="\e[4;35m"
bb="\e[4;34m"
bg="\e[4;32m"
by="\e[4;33m"
bo="\e[4;36m"

## dark colours - nested boxes
nbr="\e[9;31m"
nbp="\e[9;35m"
nbb="\e[9;34m"
nbg="\e[9;32m"
nby="\e[9;33m"
nbo="\e[9;36m"

## reset colours
end="\e[0m"

indent="    "

echo -e ${stand}${title}"Legend:${end}${stand}"
echo
echo -e "  ${r}red highlights${stand}"
echo "  - Indicates that the highlighted code contributes to the error."
echo

echo -e "  ${b}blue / ${o}cyan higlights${stand}"
echo "  - Indicates that the highlighted code is an end point of either"
echo -e "\t - a type constructor clash"
echo -e "\t - an arity clash"
echo -e "\t - a record clash"
echo -e "\t NOTE: The cyan used here is equivalent to the gray"
echo -e "\t       used by other interfaces of tthe type error slicer."

echo -e "  ${g}green highlights${stand}"
echo "  - Indicates that the highlighted code is the endpoint of a record clash."
echo

echo -e "  ${p}purple highlights${stand}"
echo "  - Indicates that the highlighted code either"
echo -e "\t - provides information about an identifier"
echo -e "\t - is expansive"
echo

echo -e "  ${y}yellow highlights${stand}"
echo "  - Indicates that the type error slicer cannot parse the file."
echo

echo -e "  ${bp}underlined text${end}${stand}"
echo "  - The use of the underline with no background highlighting is used to"
echo -e "${indent}signify that the underlined text may be irrelevant, but its presence"
echo -e "${indent}definitely contributes to the error."
echo "  - The use of the underline can indicate on of two things;"
echo -e "\t1. The application of a function to an argument (the underlined"
echo -e "\t    code) takes part in an error."
echo -e "\t2. The underlined code is the unique argument of a type name"
echo -e "\t   to make explicit that its arity is 1 (that is, it has 1 argument)."    
echo "  - NOTE: The colour of the underline can be any of those above."
echo "  - NOTE: This notation is equivalent to the box notation used in"
echo "${indent}${indent}  other interfaces to the type error slicer."
echo


echo -e "  ${bb}foo${nbr}underlined text${end}${stand}${bb}foo${end}${stand}"
echo "  - The use of the strike through effect is to use to show that the"
echo "${indent}highlighted code is in a nested underlined."
echo "  - The colour of the nested box is that of the strike through and"
echo "${indent}the colour of the external box is the colour of the underlines"
echo "${indent}which immediately precede and follow the strike through."
echo

echo -e ${end}
