.\" Process this file with
.\" groff -man -Tascii smltes-legend.1
.\"
\" ##############################################################
\" ##############################################################
\" ##
\" ## Copyright 2010 Steven Shiells
\" ##
\" ## This file is free software: you can redistribute it and/or modify
\" ## it under the terms of the GNU General Public License as published by
\" ## the Free Software Foundation, either version 3 of the License, or
\" ## (at your option) any later version.
\" ##
\" ## smltes is distributed in the hope that it will be useful,
\" ## but WITHOUT ANY WARRANTY; without even the implied warranty of
\" ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\" ## GNU General Public License for more details.
\" ##
\" ## You should have received a copy of the GNU General Public License
\" ## along with smltes.  If not, see <http://www.gnu.org/licenses/>.
\" ##
\" ## Authors: Steven Shiells
\" ## Date: January 2010
\" ##
\" ###############################################################
\" ###############################################################
.\"
.TH SMLTES-LEGEND 1 "January 2010" Linux "User Manuals"
.SH NAME
skalpel-legend \- Displays the legend explaining the slices output by smltes.
.SH SYNOPSIS
skalpel-legend
.SH DESCRIPTION
Displays a legend explaining the meaning of the different
highlighting techniques used by the type error slicer (Skalpel)
developed by the ULTRA group of Heriot-Watt University, Edinburgh.

.SH AUTHORS
Joe Wells  <jbw@macs.hw.ac.uk>

Vincent Rahli <rahli@macs.hw.ac.uk>

John Pirie <jp95@macs.hw.ac.uk>

Scott Fotheringham <sf47@macs.hw.ac.uk>

Mark Wyper <mw105@macs.hw.ac.uk>

Steven Shiells <ss215@macs.hw.ac.uk>

David Dunsmore <dd35@macs.hw.ac.uk>

.SH "SEE ALSO"
skalpel(1), skalpel-bin(1), skalpel-perl-to-bash(1).
