.\" Process this file with
.\" groff -man -Tascii skalpel-perl-to-bash.1
.\"
\" ##############################################################
\" ##############################################################
\" ##
\" ## Copyright 2011 John Pirie
\" ## Copyright 2010 Steven Shiells
\" ##
\" ## This file is free software: you can redistribute it and/or modify
\" ## it under the terms of the GNU General Public License as published by
\" ## the Free Software Foundation, either version 3 of the License, or
\" ## (at your option) any later version.
\" ##
\" ## Skalpel is distributed in the hope that it will be useful,
\" ## but WITHOUT ANY WARRANTY; without even the implied warranty of
\" ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\" ## GNU General Public License for more details.
\" ##
\" ## You should have received a copy of the GNU General Public License
\" ## along with Skalpel.  If not, see <http://www.gnu.org/licenses/>.
\" ##
\" ## Authors: Steven Shiells
\" ## Date: January 2010
\" ##
\" ###############################################################
\" ###############################################################
.TH SKALPEL-PERL-TO-BASH 1 "January 2010" Linux "User Manuals"
.SH NAME
skalpel-perl-to-bash \- converts the Perl output from
.I skalpel
to bash format so that the output can be viewed in a terminal window.
.SH SYNOPSIS
skalpel-perl-to-bash [SML-INPUT] [PERL-ERRORS]

.RS
where
[SML-INPUT] is the SML file the type error slicer was ran on and

[PERL-ERRORS] is the Perl output from the type error slicer.
.RE
.SH DESCRIPTION
Converts the Perl output from
.I skalpel
to bash format so that the output can be viewed in a terminal window.
.SH AUTHORS
Joe Wells  <jbw@macs.hw.ac.uk>

Vincent Rahli <rahli@macs.hw.ac.uk>

John Pirie <jp95@macs.hw.ac.uk>

Scott Fotheringham <sf47@macs.hw.ac.uk>

Mark Wyper <mw105@macs.hw.ac.uk>

Steven Shiells <ss215@macs.hw.ac.uk>

David Dunsmore <dd35@macs.hw.ac.uk>

.SH "SEE ALSO"
skalpel(1),  skalpel-bin(1), skalpel-legend(1).
